/**
 * Tapis Files API
 * My API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: cicsupport@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { respLinks } from '../../ng-tapis-systems-client/model/respLinks';


export interface FileInfo { 
    name?: string;
    path?: string;
    lastModified?: string;
    length?: number;
    permissions?: string;
    format?: string;
    mimeType?: string;
    type?: string;
    system?: string,
    _links?: respLinks;
    selected?: boolean;
}

